name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37ef6208f934813e9dc64d8e285d478b4058ea03c8ae705fe2421922adc46e9f"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
