name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bca54a700ff0b9b27d54368ee79ae2c72842c98ac6b96204154d19ea0b310ab8"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
