name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7634c924c97e700534feafc741472138f7d6c485fc64bb324739e70ba3aea570"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
