name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "876a3db518d3b93893c4b0c17c0e12a1472b560b3101278dc914c6785ef7b98f"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
