name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20d56ab34baeba15f1c57d9b00d2bf5ef3730435c8bf92a9962206dde46a7f30"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
